spring:
  web-flux:
    base-path: "/persistence"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

sales:
  controller:
    path: "persistence/"
    order-path: "order"

server:
  port: 8081