apiVersion: apps/v1
kind: Deployment
metadata:
  name: security
  namespace: default
spec:
  selector:
    matchLabels:
      app: security
  replicas: 1
  template:
    metadata:
      labels:
        app: security
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: security
          image: martinezhenry/security:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m